mutation live_addToBookmark($liveId: Int!){
    live_addToBookmark(liveId: $liveId){
        code
        value
        description
    }
}

mutation live_removeFromBookmark($liveId: Int!){
    live_removeFromBookmark(liveId: $liveId){
        code
        value
        description
    }
}

mutation live_createNotInterested($liveId: Int!){
    live_createNotInterested(liveId: $liveId){
        code
        value
        description
    }
}