query live_getLives($skip: Int, $take: Int, $where: LiveDtoFilterInput, $order: [LiveDtoSortInput!] ){
    live_getLives{
        result(skip: $skip, take: $take, where: $where, order: $order){
            pageInfo{
                hasNextPage
                hasPreviousPage
            }
            items{
                live{
                    userId
                    liveType
                    photoUrl
                    title
                    description
                    proposalTitle
                    proposalCategory
                    proposalSummary
                    isDraft
                    category
                    price
                    isFree
                    previewUrl
                    value
                    funding
                    setSchedule
                    publishingScheduleDate
                    publishingScheduleTime
                    viewCount
                    purchaseCount
                    user{
                        username
                        phoneNumber
                        photoUrl
                        fullName
                        about
                        gender
                        lastSeen
                        isVerified
                        isDeleted
                        createdDate
                        id
                        email
                        emailConfirmed
                        phoneNumberConfirmed
                    }
                    id
                    isDeleted
                    createdDate
                    lastModifiedDate
                }
                recordStarted
                recordEnded
                isViewed
                isBookmark
            }
            totalCount
        }
        status
    }
}

query live_getLiveStreams ($skip: Int, $take: Int, $where: LiveDtoFilterInput, $order: [LiveDtoSortInput!]){
  live_getLiveStreams {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      pageInfo{
        hasNextPage
        hasPreviousPage
      }
      items{
        isBookmark
        isPurchased
        isViewed
        live{
          category
          createdDate
          description
          liveType
          photoUrl
          title
          viewCount
        }
        recordEnded
        recordStarted
        
      }
      totalCount
    }
    status
  }
}


query live_getRecommendedLives($skip: Int, $take: Int, $where: LiveDtoFilterInput, $order: [LiveDtoSortInput!]){
  live_getRecommendedLives {
    result(skip: $skip, take: $take, where: $where, order: $order) {
           pageInfo{
        hasNextPage
        hasPreviousPage
      }
      items{
        isBookmark
        isPurchased
        isViewed
        live{
          category
          createdDate
          description
          liveType
          photoUrl
          title
          viewCount
          user{
            photoUrl
            fullName
          }
        }
        recordEnded
        recordStarted
        
      }
      totalCount
    }
    status
  }
}



query live_getTrendingLives($skip: Int, $take: Int, $where: LiveDtoFilterInput, $order: [LiveDtoSortInput!]){
  live_getTrendingLives {
    result(skip: $skip, take: $take, where: $where, order: $order) {
             pageInfo{
        hasNextPage
        hasPreviousPage
      }
      items{
        isBookmark
        isPurchased
        isViewed
        live{
          category
          createdDate
          description
          liveType
          photoUrl
          title
          viewCount
        }
        recordEnded
        recordStarted
        
      }
      totalCount
    }
    status
    }
}

query live_getNewLives($skip: Int, $take: Int, $where: LiveDtoFilterInput, $order: [LiveDtoSortInput!]){
  live_getNewLives {
    result(skip: $skip, take: $take, where: $where, order: $order) {
             pageInfo{
        hasNextPage
        hasPreviousPage
      }
      items{
        isBookmark
        isPurchased
        isViewed
        live{
          category
          createdDate
          description
          liveType
          photoUrl
          title
          viewCount
          user{
            photoUrl
            fullName
          }
        }
        recordEnded
        recordStarted
        
      }
      totalCount
    }
    status
    }
}