mutation message_createDirectMessage($input: MessageInput, $receiverId: Int!){
    message_createDirectMessage(input: $input, receiverId: $receiverId){
        result{
            createdAt
            id
        }
        status
    }
}