mutation agora_createToken($channelName: String, $publisher: Boolean!){
    agora_createToken(channelName: $channelName, publisher: $publisher){
        result
        status
    }
}


mutation agora_stopRecord($channelName: String){
  agora_stopRecord(channelName: $channelName) {
    code
    value
    description
  }
}
