import React from 'react';
import {PressableProps, Pressable} from 'react-native';
import {generateShadowUsingNumber} from '~/utils/style';

type PressProps = {
  children?: PressableProps['children'];
} & PressableProps &
  StackProps;

export default function AppPressable({
  children,
  flexDirection,
  flexGrow,
  opacity,
  borderStyle,
  flexWrap,
  flexShrink,
  m,
  mb,
  mt,
  ml,
  mr,
  mx,
  my,
  p,
  pb,
  pt,
  pl,
  pr,
  px,
  py,
  bg,
  h,
  w,
  maxW,
  maxH,
  minH,
  minW,
  alignItems,
  alignSelf,
  justifyContent,
  flex,
  overflow,
  rounded,
  borderRadius,
  borderBottomEndRadius,
  borderBottomStartRadius,
  borderTopStartRadius,
  borderTopEndRadius,
  borderTopRightRadius,
  borderTopLeftRadius,
  borderBottomLeftRadius,
  borderBottomRightRadius,
  borderColor,
  borderBottomColor,
  borderTopColor,
  borderRightColor,
  borderLeftColor,
  borderStartColor,
  borderEndColor,
  borderWidth,
  borderBottomWidth,
  borderTopWidth,
  borderRightWidth,
  borderLeftWidth,
  left,
  right,
  start,
  end,
  top,
  bottom,
  position,
  zIndex,
  shadow,
  ...props
}: PressProps) {
  const shadowStyle = shadow ? generateShadowUsingNumber(shadow) : undefined;

  return (
    <Pressable
      style={[
        props.style,
        {
          flexDirection,
          flexGrow,
          opacity,
          borderStyle,
          flexWrap,
          flexShrink,
          margin: m,
          marginBottom: mb,
          marginTop: mt,
          marginRight: mr,
          marginLeft: ml,
          marginHorizontal: mx,
          marginVertical: my,
          padding: p,
          paddingBottom: pb,
          paddingTop: pt,
          paddingRight: pr,
          paddingLeft: pl,
          paddingHorizontal: px,
          paddingVertical: py,
          backgroundColor: bg,
          height: h,
          width: w,
          maxWidth: maxW,
          maxHeight: maxH,
          minHeight: minH,
          minWidth: minW,
          alignItems,
          alignSelf,
          justifyContent,
          flex,
          overflow,
          borderRadius: rounded ?? borderRadius,
          borderBottomEndRadius,
          borderBottomStartRadius,
          borderTopStartRadius,
          borderTopRightRadius,
          borderTopLeftRadius,
          borderTopEndRadius,
          borderBottomLeftRadius,
          borderBottomRightRadius,
          borderColor,
          borderBottomColor,
          borderTopColor,
          borderRightColor,
          borderLeftColor,
          borderStartColor,
          borderEndColor,
          borderWidth,
          borderBottomWidth,
          borderTopWidth,
          borderRightWidth,
          borderLeftWidth,
          left,
          right,
          start,
          end,
          top,
          bottom,
          position,
          zIndex,
          ...shadowStyle,
        },
      ]}
      {...props}>
      {children}
    </Pressable>
  );
}
