query user_getCurrentUser{
    user_getCurrentUser{
        result{
            username
            phoneNumber
            photoUrl
            fullName
            about
            location
            age
            dateOfBirth
            gender
            lastSeen
            userType
            userRole
            isPrivateAccount
            stripeConnectAccountId
            stripeConnectCompleted
            isVerified
            verificationPhotos
            verificationErrors
            socialLinks
            profession
            yearsOfExperience
            height
            favoriteCategories
            isDeleted
            createdDate
            id
            email
            emailConfirmed
            phoneNumberConfirmed
            twoFactorEnabled
        }
        status
    }
}

query user_getUsers($skip: Int, $take: Int, $where: UserFilterInput, $order: [UserSortInput!]){
    user_getUsers{
        result(skip: $skip, take: $take, where: $where, order: $order){
            pageInfo{
                hasNextPage
                hasPreviousPage
            }
            items{
                username
                phoneNumber
                photoUrl
                fullName
                about
                location
                age
                dateOfBirth
                gender
                lastSeen
                userType
                userRole
                isPrivateAccount
                stripeConnectAccountId
                stripeConnectCompleted
                isVerified
                verificationPhotos
                verificationErrors
                socialLinks
                profession
                yearsOfExperience
                height
                favoriteCategories
                isDeleted
                createdDate
                id
                email
                emailConfirmed
                phoneNumberConfirmed
                twoFactorEnabled
            }
            totalCount
        }
        status
    }
}

query user_getCastersToFollow($skip: Int, $take: Int, $where: UserFilterInput, $order: [UserSortInput!]){
    user_getCastersToFollow{
        result(skip: $skip, take: $take, where: $where, order: $order){
            pageInfo{
                hasNextPage
                hasPreviousPage
            }
            items{
                followerCount
                followeeCount
                username
                phoneNumber
                normalizedUserName
                photoUrl
                fullName
                gender
                lastSeen
                userType
                userRole
                isVerified
                reviewCount
                isDeleted
                lastModifiedDate
                createdDate
                id
                email
            }
            totalCount
        }
        status
    }
}